/**
 * In-memory TTL cache mapping Discord message IDs to their voice transcripts.
 *
 * Two sources are tracked:
 *   - "user_stt"  — audio message sent by a user, transcribed via ElevenLabs STT.
 *                   Displayed with a [System: ...] prefix so the LLM knows it was
 *                   originally a voice message.
 *   - "tts"       — audio message generated by Tomori via the generate_voice_message
 *                   tool. The caption text is cached here so history formatting can
 *                   show the clean text without re-running STT on the audio file.
 *
 * Cache entries expire after VOICE_TRANSCRIPT_CACHE_TTL_MINUTES (default: 120 min).
 * On expiry, audio messages in history fall back to [Attachment: filename.mp3].
 * The current-turn message is always re-STT'd fresh before trigger detection runs,
 * so the cache miss penalty only applies to older history messages.
 */

const DEFAULT_TTL_MINUTES = 120;

/** Public shape returned on cache hit. */
export interface VoiceTranscriptEntry {
	/** Raw transcript text, without any system prefix. */
	transcript: string;
	/** Whether the audio was produced by the user (STT) or by Tomori (TTS). */
	source: "user_stt" | "tts";
}

interface StoredEntry extends VoiceTranscriptEntry {
	cachedAt: number;
}

const cache = new Map<string, StoredEntry>();

function getTtlMs(): number {
	const parsed = Number.parseInt(
		process.env.VOICE_TRANSCRIPT_CACHE_TTL_MINUTES ?? "",
		10,
	);
	const minutes =
		Number.isFinite(parsed) && parsed > 0 ? parsed : DEFAULT_TTL_MINUTES;
	return minutes * 60 * 1_000;
}

/**
 * Retrieve a cached transcript for a Discord message ID.
 * Returns null on miss or expiry (and evicts the stale entry).
 */
export function getCachedVoiceTranscript(
	messageId: string,
): VoiceTranscriptEntry | null {
	const entry = cache.get(messageId);
	if (!entry) return null;

	if (Date.now() - entry.cachedAt > getTtlMs()) {
		cache.delete(messageId);
		return null;
	}

	return { transcript: entry.transcript, source: entry.source };
}

/**
 * Store a transcript for a Discord message ID.
 * Overwrites any existing entry for the same ID.
 */
export function setCachedVoiceTranscript(
	messageId: string,
	transcript: string,
	source: "user_stt" | "tts",
): void {
	cache.set(messageId, { transcript, source, cachedAt: Date.now() });
}
