// Typed NovelAI sampling preset catalog: generated from the former 03_nai_presets.sql seed.

import type { CatalogSection, NaiPresetInput } from "./types";

export const naiPresetSections: CatalogSection<NaiPresetInput>[] = [
  {
    comment: ["============ KAYRA PRESETS ============", "Carefree-Kayra (DEFAULT for kayra-v1)"],
    rows: [
      {
        name: "Carefree-Kayra",
        modelTarget: "kayra",
        isDefault: true,
        desc: "Balanced and relaxed, a reliable all-purpose preset for natural roleplay.",
        i18n: {
          ja: "バランスが取れたリラックスしたプリセット。自然なロールプレイに最適。",
          "pt-BR": "Equilibrada e relaxada, uma predefinição versátil e confiável para roleplay natural.",
          "es-419": "Equilibrado y relajado, preajuste confiable para roleplay natural.",
          "zh-TW": "均衡放鬆、穩定可靠的全方位預設集，適合自然的角色扮演。",
          vi: "Cân bằng và thư thái, preset đa năng tin cậy cho nhập vai tự nhiên.",
          "zh-CN": "均衡放松、稳定可靠的全能预设集，适合自然的角色扮演。",
        },
        parameters: {
          order: [2, 3, 0, 4, 1],
          temperature: 1.35,
          max_length: 150,
          min_length: 1,
          top_k: 15,
          top_p: 0.85,
          top_a: 0.1,
          tail_free_sampling: 0.915,
          repetition_penalty: 2.8,
          repetition_penalty_range: 2048,
          repetition_penalty_slope: 0.02,
          repetition_penalty_frequency: 0.02,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "aggressive",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Asper-Kayra",
    rows: [
      {
        name: "Asper-Kayra",
        modelTarget: "kayra",
        desc: "Crisp and focused, lower temperature with Typical Sampling for steady, disciplined prose.",
        i18n: {
          ja: "温度低めでTypical Samplingを使用。落ち着いた規律ある文体に最適。",
          "pt-BR": "Focada e precisa, temperatura menor com Typical Sampling para prosa firme e disciplinada.",
          "es-419": "Preciso y enfocado, con menor temperatura y Typical Sampling para prosa firme.",
          "zh-TW": "俐落專注，以較低溫度和 Typical Sampling 換取沉穩有紀律的文筆。",
          vi: "Sắc nét và tập trung, nhiệt độ thấp cùng Typical Sampling cho văn phong ổn định, kỷ luật.",
          "zh-CN": "利落专注，以较低温度和 Typical Sampling 换取沉稳有纪律的文笔。",
        },
        parameters: {
          order: [5, 0, 1, 3],
          temperature: 1.16,
          max_length: 150,
          min_length: 1,
          top_k: 175,
          typical_p: 0.96,
          tail_free_sampling: 0.994,
          repetition_penalty: 1.68,
          repetition_penalty_range: 2240,
          repetition_penalty_slope: 1.5,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0.005,
          phrase_rep_pen: "medium",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Blended-Coffee-Kayra",
    rows: [
      {
        name: "Blended-Coffee-Kayra",
        modelTarget: "kayra",
        desc: "Smooth and grounded, blends top-K and tail-free for consistent, natural storytelling.",
        i18n: {
          ja: "トップKとテールフリーを組み合わせた滑らかで安定した文体。",
          "pt-BR": "Suave e realista, mistura top-K e tail-free para narração natural e consistente.",
          "es-419": "Suave y estable, combina top-K y tail-free para una narración natural.",
          "zh-TW": "平順扎實，混合 top-K 與 tail-free，故事敘述一致而自然。",
          vi: "Mượt mà và thực tế, kết hợp top-K và tail-free cho lời kể nhất quán, tự nhiên.",
          "zh-CN": "平顺扎实，混合 top-K 与 tail-free，故事叙述一致而自然。",
        },
        parameters: {
          order: [0, 1, 2, 3],
          temperature: 1.0,
          max_length: 150,
          min_length: 1,
          top_k: 25,
          top_p: 1.0,
          tail_free_sampling: 0.925,
          repetition_penalty: 1.6,
          repetition_penalty_frequency: 0.001,
          repetition_penalty_range: 0,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "medium",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Blook-Kayra",
    rows: [
      {
        name: "Blook-Kayra",
        modelTarget: "kayra",
        desc: "Bold repetition-fighter, very aggressive phrase rep penalty keeps outputs fresh and varied.",
        i18n: {
          ja: "非常に攻撃的なフレーズ繰り返しペナルティで新鮮でバラエティ豊かな出力を実現。",
          "pt-BR": "Combate repetições, penalidade de frase agressiva mantém as respostas variadas.",
          "es-419": "Combate repeticiones con una penalización agresiva para respuestas variadas.",
          "zh-TW": "大膽對抗重複，極強烈的片語重複懲罰讓輸出保持新鮮多變。",
          vi: "Chống lặp mạnh mẽ, phạt lặp cụm từ quyết liệt giúp kết quả luôn tươi mới và đa dạng.",
          "zh-CN": "大胆对抗重复，极强烈的短语重复惩罚让输出保持新鲜多变。",
        },
        parameters: {
          order: [2, 3, 1, 0],
          temperature: 1.0,
          max_length: 150,
          min_length: 1,
          top_k: 0,
          top_p: 0.96,
          tail_free_sampling: 0.96,
          repetition_penalty: 2.0,
          repetition_penalty_slope: 1.0,
          repetition_penalty_frequency: 0.02,
          repetition_penalty_range: 0,
          repetition_penalty_presence: 0.3,
          phrase_rep_pen: "very_aggressive",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "CosmicCube-Kayra",
    rows: [
      {
        name: "CosmicCube-Kayra",
        modelTarget: "kayra",
        desc: "Mirostat entropy sampling, experimental entropy-based sampler for unpredictable, cosmic outputs.",
        i18n: {
          ja: "ミロスタットエントロピーサンプリング。予測不可能で宇宙的な出力のための実験的サンプラー。",
          "pt-BR": "Amostragem Mirostat, experimental para respostas cósmicas e imprevisíveis.",
          "es-419": "Muestreo de entropía Mirostat para resultados cósmicos e impredecibles.",
          "zh-TW": "Mirostat 熵取樣，實驗性的熵取樣器，輸出難以預測、天馬行空。",
          vi: "Lấy mẫu entropy mirostat, bộ lấy mẫu theo entropy cho kết quả biến hóa, kỳ ảo.",
          "zh-CN": "Mirostat 熵采样，实验性的熵采样器，输出难以预测、天马行空。",
        },
        parameters: {
          order: [8, 5, 0, 3],
          temperature: 0.9,
          max_length: 150,
          min_length: 1,
          typical_p: 0.95,
          tail_free_sampling: 0.92,
          mirostat_lr: 0.22,
          mirostat_tau: 4.95,
          repetition_penalty: 3.0,
          repetition_penalty_range: 4000,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "off",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Fresh-Coffee-Kayra",
    rows: [
      {
        name: "Fresh-Coffee-Kayra",
        modelTarget: "kayra",
        desc: "Light and clean, fresher top-K outputs with minimal phrase repetition penalty.",
        i18n: {
          ja: "軽くクリーンなトップK出力。フレーズ繰り返しペナルティを最小化。",
          "pt-BR": "Leve e limpa, respostas top-K com penalidade mínima de repetição de frase.",
          "es-419": "Ligero y limpio, con salidas top-K frescas y mínima penalización de repetición.",
          "zh-TW": "輕盈乾淨，以最低的片語重複懲罰換取更清新的 top-K 輸出。",
          vi: "Nhẹ nhàng và trong trẻo, kết quả top-K tươi mới với phạt lặp cụm từ tối thiểu.",
          "zh-CN": "轻盈干净，以最低的短语重复惩罚换取更清新的 top-K 输出。",
        },
        parameters: {
          order: [0, 1, 2, 3],
          temperature: 1.0,
          max_length: 150,
          min_length: 1,
          top_k: 25,
          top_p: 1.0,
          tail_free_sampling: 0.925,
          repetition_penalty: 1.9,
          repetition_penalty_range: 768,
          repetition_penalty_slope: 1.0,
          repetition_penalty_frequency: 0.0025,
          repetition_penalty_presence: 0.001,
          phrase_rep_pen: "off",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Green-Active-Writer-Kayra",
    rows: [
      {
        name: "Green-Active-Writer-Kayra",
        modelTarget: "kayra",
        desc: "High-energy mirostat writer, creative and dynamic at temperature 1.5 with strong anti-repetition.",
        i18n: {
          ja: "高エネルギーなミロスタットライター。温度1.5で創造的かつダイナミック、強い反復防止付き。",
          "pt-BR": "Mirostat de alta energia, dinâmico e criativo (temp 1.5) com forte antirrepetição.",
          "es-419": "Mirostat enérgico y creativo (temp. 1.5) con fuerte control de repeticiones.",
          "zh-TW": "高能量的 Mirostat 寫手，溫度 1.5 下創意奔放，並具備強力反重複。",
          vi: "Viết bằng mirostat giàu năng lượng, sáng tạo ở nhiệt độ 1.5 cùng khả năng chống lặp mạnh.",
          "zh-CN": "高能量的 Mirostat 写手，温度 1.5 下创意奔放，并具备强力反重复。",
        },
        parameters: {
          order: [0, 8, 5, 3],
          temperature: 1.5,
          max_length: 150,
          min_length: 1,
          typical_p: 0.95,
          tail_free_sampling: 0.95,
          mirostat_lr: 0.2,
          mirostat_tau: 5.5,
          repetition_penalty: 1.0,
          repetition_penalty_range: 1632,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "very_aggressive",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Pilotfish-Kayra",
    rows: [
      {
        name: "Pilotfish-Kayra",
        modelTarget: "kayra",
        desc: "Multi-sampler blend, layered top-K/P/A/Typical for rich narrative variety.",
        i18n: {
          ja: "複数のサンプラーを組み合わせた豊かなナラティブバリエーション。",
          "pt-BR": "Mistura de amostradores top-K/P/A/Typical para rica variedade de narração.",
          "es-419": "Mezcla top-K/P/A/Typical para una gran variedad narrativa.",
          "zh-TW": "多取樣器混合，層層疊上 top-K、P、A 與 Typical，敘事變化豐富。",
          vi: "Phối hợp nhiều bộ lấy mẫu, xếp tầng top-K/P/A/Typical cho lời kể phong phú.",
          "zh-CN": "多采样器混合，层层叠上 top-K、P、A 与 Typical，叙事变化丰富。",
        },
        parameters: {
          order: [0, 4, 1, 2, 5, 3],
          temperature: 1.31,
          max_length: 150,
          min_length: 1,
          top_k: 25,
          top_p: 0.97,
          top_a: 0.18,
          typical_p: 0.98,
          tail_free_sampling: 1.0,
          repetition_penalty: 1.55,
          repetition_penalty_frequency: 0.00075,
          repetition_penalty_presence: 0.00085,
          repetition_penalty_range: 8192,
          repetition_penalty_slope: 1.8,
          phrase_rep_pen: "medium",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Pro_Writer-Kayra",
    rows: [
      {
        name: "Pro_Writer-Kayra",
        modelTarget: "kayra",
        desc: "Refined narrative, tuned for written prose quality using top-A and Typical Sampling.",
        i18n: {
          ja: "洗練されたナラティブ。トップAとTypical Samplingによる高品質な文章向け。",
          "pt-BR": "Narrativa refinada, ajustada para qualidade de prosa (top-A e Typical Sampling).",
          "es-419": "Narrativa refinada, optimizada para prosa de calidad con top-A y Typical Sampling.",
          "zh-TW": "精煉的敘事，以 top-A 與 Typical Sampling 調校出優異的書面文筆。",
          vi: "Lời văn trau chuốt, tinh chỉnh cho văn xuôi bằng top-A và Typical Sampling.",
          "zh-CN": "精炼的叙事，以 top-A 与 Typical Sampling 调校出优异的书面文笔。",
        },
        parameters: {
          order: [3, 4, 5, 0],
          temperature: 1.06,
          max_length: 150,
          min_length: 1,
          top_a: 0.146,
          typical_p: 0.976,
          tail_free_sampling: 0.969,
          repetition_penalty: 1.86,
          repetition_penalty_slope: 2.33,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          repetition_penalty_range: 2048,
          phrase_rep_pen: "medium",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Stelenes-Kayra",
    rows: [
      {
        name: "Stelenes-Kayra",
        modelTarget: "kayra",
        desc: "Maximum chaos, very high temperature (2.5) for maximally experimental and unpredictable text.",
        i18n: {
          ja: "最大カオス。温度2.5による極めて実験的で予測不可能なテキスト生成。",
          "pt-BR": "Caos máximo (temp 2.5) para textos extremamente experimentais e imprevisíveis.",
          "es-419": "Caos máximo, temperatura muy alta (2.5) para texto experimental e impredecible.",
          "zh-TW": "極度混亂，溫度 2.5 帶來最實驗、最難以預測的文字。",
          vi: "Hỗn loạn tối đa, nhiệt độ rất cao (2.5) cho văn bản giàu tính thử nghiệm và khó đoán.",
          "zh-CN": "极度混乱，温度 2.5 带来最实验、最难以预测的文字。",
        },
        parameters: {
          order: [3, 0, 5],
          temperature: 2.5,
          max_length: 150,
          min_length: 1,
          typical_p: 0.969,
          tail_free_sampling: 0.941,
          repetition_penalty: 1.0,
          repetition_penalty_range: 1024,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "medium",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Tea_Time-Kayra",
    rows: [
      {
        name: "Tea_Time-Kayra",
        modelTarget: "kayra",
        desc: "Quiet and mellow, top-A and Typical with aggressive phrase guard for tranquil outputs.",
        i18n: {
          ja: "トップAとTypical、攻撃的フレーズガードで穏やかで落ち着いた出力を実現。",
          "pt-BR": "Calma e suave, top-A e Typical com guarda de frase agressiva para saídas tranquilas.",
          "es-419": "Tranquilo y suave, top-A y Typical con control agresivo de frases.",
          "zh-TW": "安靜柔和，以 top-A、Typical 與強烈的片語防護換取平靜的輸出。",
          vi: "Yên tĩnh và êm dịu, top-A và Typical cùng khả năng chặn lặp cụm từ cho kết quả êm ả.",
          "zh-CN": "安静柔和，以 top-A、Typical 与强烈的短语防护换取平静的输出。",
        },
        parameters: {
          order: [5, 0, 4],
          temperature: 1.0,
          max_length: 150,
          min_length: 1,
          top_a: 0.017,
          typical_p: 0.975,
          repetition_penalty: 3.0,
          repetition_penalty_slope: 0.09,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          repetition_penalty_range: 7680,
          phrase_rep_pen: "aggressive",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Tesseract-Kayra",
    rows: [
      {
        name: "Tesseract-Kayra",
        modelTarget: "kayra",
        desc: "Sharp and precise, very low temperature (0.895) for highly deterministic, focused responses.",
        i18n: {
          ja: "非常に低い温度（0.895）による高度に決定論的でフォーカスした応答。",
          "pt-BR": "Afiada e precisa, temperatura baixa (0.895) para respostas determinísticas.",
          "es-419": "Agudo y preciso, temperatura muy baja (0.895) para respuestas deterministas.",
          "zh-TW": "銳利精準，極低溫（0.895）帶來高度確定、聚焦的回覆。",
          vi: "Sắc bén và chính xác, nhiệt độ rất thấp (0.895) cho phản hồi tập trung, tính xác định cao.",
          "zh-CN": "锐利精准，极低温（0.895）带来高度确定、聚焦的回复。",
        },
        parameters: {
          order: [0, 5],
          temperature: 0.895,
          max_length: 150,
          min_length: 1,
          typical_p: 0.9,
          repetition_penalty: 2.0,
          repetition_penalty_slope: 3.2,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          repetition_penalty_range: 4048,
          phrase_rep_pen: "aggressive",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Writers-Daemon-Kayra",
    rows: [
      {
        name: "Writers-Daemon-Kayra",
        modelTarget: "kayra",
        desc: "Daemon-driven mirostat, comprehensive multi-sampler with high entropy for creative writing.",
        i18n: {
          ja: "デーモン駆動のミロスタット。高エントロピーの包括的マルチサンプラーでクリエイティブライティングに最適。",
          "es-419": "Mirostat impulsado por daemon, con alta entropía para escritura creativa.",
          "zh-TW": "由 Daemon 驅動的 Mirostat，高熵的完整多取樣器組合，適合創意寫作。",
          vi: "Mirostat điều khiển bởi daemon, lấy mẫu đa năng entropy cao cho viết sáng tạo.",
          "zh-CN": "由 Daemon 驱动的 Mirostat，高熵的完整多采样器组合，适合创意写作。",
        },
        parameters: {
          order: [8, 0, 5, 3, 2, 4],
          temperature: 1.5,
          max_length: 150,
          min_length: 1,
          top_a: 0.02,
          top_p: 0.95,
          typical_p: 0.95,
          tail_free_sampling: 0.95,
          mirostat_lr: 0.25,
          mirostat_tau: 5.0,
          repetition_penalty: 1.625,
          repetition_penalty_range: 2016,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "very_aggressive",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: ["============ ERATO PRESETS ============", "Erato-Shosetsu (DEFAULT for llama-3-erato-v1)"],
    rows: [
      {
        name: "Erato-Shosetsu",
        modelTarget: "erato",
        isDefault: true,
        desc: "Novel-style writing, Shosetsu (小説) tuned for structured narrative with strong rep control.",
        i18n: {
          ja: "「小説」スタイル。整理されたナラティブと強い反復制御に最適化。",
          "pt-BR": "Estilo romance, Shosetsu (小説) ajustado para narrativa estruturada e controle de repetição.",
          "es-419": "Estilo novela, Shosetsu (小説) para narrativa estructurada y control de repeticiones.",
          "zh-TW": "小說風格，Shosetsu（小説）調校出結構完整的敘事與強力重複控制。",
          vi: "Văn phong tiểu thuyết, Shosetsu (小説) tinh chỉnh cho tự sự có cấu trúc, kiểm soát lặp.",
          "zh-CN": "小说风格，Shosetsu（小説）调校出结构完整的叙事与强力重复控制。",
        },
        parameters: {
          order: [9, 10],
          temperature: 1.0,
          max_length: 150,
          min_length: 1,
          top_k: 50,
          top_p: 0.85,
          top_a: 1.0,
          typical_p: 1.0,
          tail_free_sampling: 0.895,
          repetition_penalty: 1.63,
          repetition_penalty_range: 1024,
          repetition_penalty_slope: 3.33,
          repetition_penalty_frequency: 0.0035,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "medium",
          mirostat_lr: 1.0,
          mirostat_tau: 0,
          min_p: 0.05,
        },
      },
    ],
  },
  {
    comment: "Erato-Dragonfruit",
    rows: [
      {
        name: "Erato-Dragonfruit",
        modelTarget: "erato",
        desc: "Fruity and vivid, complex sampler chain with mirostat for elaborate and colorful prose.",
        i18n: {
          ja: "複雑なサンプラーチェーンとミロスタットで鮮やかで精巧な文体を実現。",
          "pt-BR": "Vívida, cadeia complexa de amostradores com mirostat para prosa colorida e elaborada.",
          "es-419": "Vívido, con cadena compleja de muestreo y mirostat para prosa elaborada y colorida.",
          "zh-TW": "鮮活多彩，複雜的取樣器鏈搭配 Mirostat，文筆精緻絢麗。",
          vi: "Sống động và sắc sảo, chuỗi lấy mẫu phức tạp với mirostat cho văn phong trau chuốt, rực rỡ.",
          "zh-CN": "鲜活多彩，复杂的采样器链搭配 Mirostat，文笔精致绚丽。",
        },
        parameters: {
          order: [0, 5, 9, 10, 8, 4],
          temperature: 1.37,
          max_length: 150,
          min_length: 1,
          top_k: 0,
          top_p: 1.0,
          top_a: 0.1,
          typical_p: 0.875,
          tail_free_sampling: 0.87,
          repetition_penalty: 3.25,
          repetition_penalty_range: 6000,
          repetition_penalty_slope: 3.25,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "off",
          mirostat_lr: 0.2,
          mirostat_tau: 4.0,
          min_p: 0.035,
        },
      },
    ],
  },
  {
    comment: "Erato-Golden Arrow",
    rows: [
      {
        name: "Erato-Golden Arrow",
        modelTarget: "erato",
        desc: "Classic and balanced, standard tail-free sampling for coherent, flowing narrative.",
        i18n: {
          ja: "クラシックでバランスの取れた、テールフリーサンプリングによる一貫した滑らかなナラティブ。",
          "pt-BR": "Clássica e equilibrada, tail-free padrão para uma narrativa coerente e fluida.",
          "es-419": "Clásico y equilibrado, tail-free estándar para narrativa coherente y fluida.",
          "zh-TW": "經典均衡，標準 tail-free 取樣，敘事連貫流暢。",
          vi: "Cổ điển và cân bằng, tail-free sampling chuẩn cho lời văn mạch lạc, trôi chảy.",
          "zh-CN": "经典均衡，标准 tail-free 采样，叙事连贯流畅。",
        },
        parameters: {
          order: [9, 2],
          temperature: 1.0,
          max_length: 150,
          min_length: 1,
          top_k: 0,
          top_p: 0.995,
          top_a: 1.0,
          typical_p: 1.0,
          tail_free_sampling: 0.87,
          repetition_penalty: 1.5,
          repetition_penalty_range: 2240,
          repetition_penalty_slope: 1.0,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "light",
          mirostat_lr: 1.0,
          mirostat_tau: 0,
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Erato-Wilder",
    rows: [
      {
        name: "Erato-Wilder",
        modelTarget: "erato",
        desc: "Wild and expansive, high top-K (300) for more varied and adventurous outputs.",
        i18n: {
          ja: "高いトップK（300）による多様で冒険的な出力。",
          "pt-BR": "Selvagem e expansiva, alto top-K (300) para resultados mais aventureiros.",
          "es-419": "Salvaje y amplio, top-K alto (300) para resultados variados y aventureros.",
          "zh-TW": "狂野奔放，高 top-K（300）帶來更多變化與冒險感的輸出。",
          vi: "Phóng khoáng và rộng mở, top-K cao (300) cho kết quả đa dạng và phiêu lưu hơn.",
          "zh-CN": "狂野奔放，高 top-K（300）带来更多变化与冒险感的输出。",
        },
        parameters: {
          order: [9, 10],
          temperature: 1.0,
          max_length: 150,
          min_length: 1,
          top_k: 300,
          top_p: 0.98,
          top_a: 0.004,
          typical_p: 0.96,
          tail_free_sampling: 0.96,
          repetition_penalty: 1.48,
          repetition_penalty_range: 2240,
          repetition_penalty_slope: 0.64,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "medium",
          mirostat_lr: 1.0,
          mirostat_tau: 0,
          min_p: 0.02,
        },
      },
    ],
  },
  {
    comment: "Erato-Zany Scribe",
    rows: [
      {
        name: "Erato-Zany Scribe",
        modelTarget: "erato",
        desc: "Zany and unpredictable, high frequency/presence penalties for maximally varied outputs.",
        i18n: {
          ja: "高い頻度・存在ペナルティによる最大限に多様な出力。",
          "pt-BR": "Excêntrica, altas penalidades de presença/frequência para máxima variedade.",
          "es-419": "Excéntrico e impredecible, con altas penalizaciones para máxima variedad.",
          "zh-TW": "古怪難料，高頻率與存在懲罰讓輸出變化最大化。",
          vi: "Biến ảo và khó đoán, phạt tần suất/hiện diện cao cho kết quả đa dạng tối đa.",
          "zh-CN": "古怪难料，高频率与存在惩罚让输出变化最大化。",
        },
        parameters: {
          order: [9, 2],
          temperature: 1.0,
          max_length: 150,
          min_length: 1,
          top_k: 0,
          top_p: 0.99,
          top_a: 1.0,
          typical_p: 1.0,
          tail_free_sampling: 0.99,
          repetition_penalty: 1.0,
          repetition_penalty_range: 64,
          repetition_penalty_slope: 1.0,
          repetition_penalty_frequency: 0.75,
          repetition_penalty_presence: 1.5,
          phrase_rep_pen: "medium",
          mirostat_lr: 1.0,
          mirostat_tau: 1.0,
          min_p: 0.08,
        },
      },
    ],
  },
];
