/**
 * Default NovelAI prompt tags persisted in server config.
 * These mirror the schema defaults in `src/db/schema.sql`.
 */
export const DEFAULT_NAI_STYLE_TAGS = [
	"8k",
	"absurdres",
	"masterpiece",
	"best quality",
	"good quality",
	"newest",
];

export const DEFAULT_NAI_NEGATIVE_TAGS = [
	"lowres",
	"worst quality",
	"low quality",
	"bad quality",
	"old",
	"oldest",
	"unfinished",
	"scan artifacts",
	"jpeg artifacts",
	"jaggy lines",
	"unclear",
	"sketch",
	"blurry",
	"bad anatomy",
	"very displeasing",
	"displeasing",
	"bad hands",
	"bad fingers",
	"missing fingers",
	"bad proportions",
	"bad perspective",
	"bad eyes",
	"bad pupils",
	"multiple heads",
	"extra faces",
	"many arms",
	"poorly drawn face",
	"poorly drawn hands",
	"fused hands",
	"bad feet",
	"too many legs",
	"malformed limbs",
	"extra arms",
	"multiple ears",
	"fat",
	"mutation",
	"monster",
	"amputee",
	"guro",
	"extra digits",
	"fewer digits",
	"twitter username",
	"username",
	"watermark",
	"signature",
	"2koma",
	"4koma",
	"comic",
];
