export interface LandingFeatureCopy {
  title: string;
  description: string;
}

export interface LandingCopy {
  title: string;
  description: string;
  heading: string;
  developmentStatus: string;
  readDocs: string;
  invite: string;
  viewGitHub: string;
  theme: string;
  language: string;
  dark: string;
  light: string;
  automatic: string;
  home: string;
  links: string;
  support: string;
  showcase: string;
  chooseFeature: string;
  viewFeature: string;
  galleryInstruction: string;
  guide: string;
  documentationLanguages: string;
  heroImage: string;
  features: readonly LandingFeatureCopy[];
}

export const landingCopyByLocale: Record<string, LandingCopy> = {
  en: {
    title: "TomoriBot | Open-Source AI Agent & Roleplay Bot for Discord",
    description:
      "TomoriBot is a free, open-source Discord bot with persistent memory, multiple personas, agentic tools, media generation, and support for hosted or local AI models.",
    heading: "Open-source AI for Discord",
    developmentStatus: "Currently in active development",
    readDocs: "Read the docs",
    invite: "Invite TomoriBot",
    viewGitHub: "View on GitHub",
    theme: "Theme",
    language: "Language",
    dark: "Dark",
    light: "Light",
    automatic: "Auto",
    home: "TomoriBot home",
    links: "TomoriBot links",
    support: "Support on Ko-fi",
    showcase: "TomoriBot feature gallery",
    chooseFeature: "Choose a feature",
    viewFeature: "View",
    galleryInstruction: "Click the left or right half to move through the gallery.",
    guide: "Open the complete TomoriBot guide in any published language.",
    documentationLanguages: "Documentation languages",
    heroImage: "TomoriBot",
    features: [
      {
        title: "Multiple Personas",
        description: "Run several custom characters in one server, each with their own settings, memories, and avatars.",
      },
      {
        title: "Persistent Memory",
        description: "Keep useful context across conversations, channels, and servers with server and personal memories.",
      },
      {
        title: "Media Generation",
        description: "Understand and generate images, short videos, and voice messages directly inside Discord.",
      },
      {
        title: "Agentic Tools",
        description: "Search the web, schedule reminders, use custom MCP tools, and complete multi-step tasks.",
      },
      {
        title: "Fully Local Setup",
        description: "Self-host with local models, ComfyUI, SearXNG, voice servers, and MCP integrations.",
      },
      {
        title: "Server Moderation",
        description: "Control access and costs with quotas, permissions, channel rules, role rules, and audit tools.",
      },
      {
        title: "200+ Commands",
        description: "Configure personas, providers, prompts, models, tools, memory, and permissions from Discord.",
      },
      {
        title: "SillyTavern Support",
        description: "Import SillyTavern prompt presets and character cards for use directly in Discord.",
      },
    ],
  },
  ja: {
    title: "TomoriBot | Discord向けオープンソースAIエージェント＆ロールプレイボット",
    description:
      "TomoriBotは、永続メモリ、複数のペルソナ、エージェントツール、メディア生成、クラウドまたはローカルAIモデルへの対応を備えた無料のオープンソースDiscordボットです。",
    heading: "DiscordのためのオープンソースAI",
    developmentStatus: "現在開発中",
    readDocs: "ドキュメントを読む",
    invite: "TomoriBotを招待",
    viewGitHub: "GitHubで見る",
    theme: "テーマ",
    language: "言語",
    dark: "ダーク",
    light: "ライト",
    automatic: "自動",
    home: "TomoriBotホーム",
    links: "TomoriBotのリンク",
    support: "Ko-fiで支援",
    showcase: "TomoriBot機能ギャラリー",
    chooseFeature: "機能を選択",
    viewFeature: "表示",
    galleryInstruction: "ギャラリー内を移動するには左右半分をクリックしてください。",
    guide: "公開済みの言語でTomoriBotの完全ガイドを読むことができます。",
    documentationLanguages: "ドキュメントの言語",
    heroImage: "TomoriBot",
    features: [
      { title: "複数のペルソナ", description: "1つのサーバーで、設定、メモリ、アバターがそれぞれ異なる複数のカスタムキャラクターを使えます。" },
      { title: "永続メモリ", description: "サーバーと個人のメモリにより、会話、チャンネル、サーバーをまたいで役立つコンテキストを維持します。" },
      { title: "メディア生成", description: "Discord内で画像、短い動画、音声メッセージを理解し、生成します。" },
      { title: "エージェントツール", description: "Web検索、リマインダーの予定設定、カスタムMCPツールの利用、複数手順のタスク実行ができます。" },
      { title: "完全ローカル構成", description: "ローカルモデル、ComfyUI、SearXNG、音声サーバー、MCP連携を使ってセルフホストできます。" },
      { title: "サーバー管理", description: "クォータ、権限、チャンネルルール、ロールルール、監査ツールでアクセスとコストを管理します。" },
      { title: "200以上のコマンド", description: "Discordからペルソナ、プロバイダー、プロンプト、モデル、ツール、メモリ、権限を設定できます。" },
      { title: "SillyTavern対応", description: "SillyTavernのプロンプトプリセットとキャラクターカードをDiscord内で直接利用できます。" },
    ],
  },
  "zh-TW": {
    title: "TomoriBot | Discord 開源 AI 代理與角色扮演機器人",
    description: "TomoriBot 是免費、開源的 Discord 機器人，具備持久記憶、多個角色、代理工具、媒體生成，以及託管與本機 AI 模型支援。",
    heading: "Discord 的開源 AI",
    developmentStatus: "目前正在積極開發中",
    readDocs: "閱讀文件",
    invite: "邀請 TomoriBot",
    viewGitHub: "在 GitHub 上查看",
    theme: "主題",
    language: "語言",
    dark: "深色",
    light: "淺色",
    automatic: "自動",
    home: "TomoriBot 首頁",
    links: "TomoriBot 連結",
    support: "在 Ko-fi 支持我們",
    showcase: "TomoriBot 功能圖庫",
    chooseFeature: "選擇功能",
    viewFeature: "查看",
    galleryInstruction: "點擊左右半邊以瀏覽圖庫。",
    guide: "以任何已發布語言閱讀完整的 TomoriBot 指南。",
    documentationLanguages: "文件語言",
    heroImage: "TomoriBot",
    features: [
      { title: "多個角色", description: "在同一伺服器中使用多個自訂角色，每個角色都有自己的設定、記憶與頭像。" },
      { title: "持久記憶", description: "透過伺服器與個人記憶，在對話、頻道與伺服器之間保留有用的內容。" },
      { title: "媒體生成", description: "直接在 Discord 中理解並生成圖片、短片與語音訊息。" },
      { title: "代理工具", description: "搜尋網路、排定提醒、使用自訂 MCP 工具，並完成多步驟任務。" },
      { title: "完全本機部署", description: "使用本機模型、ComfyUI、SearXNG、語音伺服器與 MCP 整合自行託管。" },
      { title: "伺服器管理", description: "透過配額、權限、頻道規則、身分組規則與稽核工具控制存取與成本。" },
      { title: "超過 200 個指令", description: "可直接從 Discord 設定角色、提供者、提示詞、模型、工具、記憶與權限。" },
      { title: "支援 SillyTavern", description: "直接在 Discord 中使用 SillyTavern 提示詞預設與角色卡。" },
    ],
  },
  "zh-CN": {
    title: "TomoriBot | 面向 Discord 的开源 AI 智能体与角色扮演机器人",
    description: "TomoriBot 是免费、开源的 Discord 机器人，具备持久记忆、多个角色、智能体工具、媒体生成，以及托管和本地 AI 模型支持。",
    heading: "面向 Discord 的开源 AI",
    developmentStatus: "目前正在积极开发中",
    readDocs: "阅读文档",
    invite: "邀请 TomoriBot",
    viewGitHub: "在 GitHub 上查看",
    theme: "主题",
    language: "语言",
    dark: "深色",
    light: "浅色",
    automatic: "自动",
    home: "TomoriBot 首页",
    links: "TomoriBot 链接",
    support: "在 Ko-fi 支持我们",
    showcase: "TomoriBot 功能图库",
    chooseFeature: "选择功能",
    viewFeature: "查看",
    galleryInstruction: "点击左右半边以浏览图库。",
    guide: "以任何已发布语言阅读完整的 TomoriBot 指南。",
    documentationLanguages: "文档语言",
    heroImage: "TomoriBot",
    features: [
      { title: "多个角色", description: "在同一服务器中使用多个自定义角色，每个角色都有自己的设置、记忆和头像。" },
      { title: "持久记忆", description: "通过服务器和个人记忆，在对话、频道和服务器之间保留有用的上下文。" },
      { title: "媒体生成", description: "直接在 Discord 中理解并生成图片、短视频和语音消息。" },
      { title: "智能体工具", description: "搜索网络、安排提醒、使用自定义 MCP 工具，并完成多步骤任务。" },
      { title: "完全本地部署", description: "使用本地模型、ComfyUI、SearXNG、语音服务器和 MCP 集成自行托管。" },
      { title: "服务器管理", description: "通过配额、权限、频道规则、身份组规则和审计工具控制访问与成本。" },
      { title: "200 多个命令", description: "可直接从 Discord 配置角色、提供商、提示词、模型、工具、记忆和权限。" },
      { title: "支持 SillyTavern", description: "直接在 Discord 中使用 SillyTavern 提示词预设和角色卡。" },
    ],
  },
  "es-419": {
    title: "TomoriBot | Agente de IA y bot de rol de código abierto para Discord",
    description: "TomoriBot es un bot de Discord gratuito y de código abierto con memoria persistente, múltiples personajes, herramientas de agente, generación multimedia y compatibilidad con modelos de IA alojados o locales.",
    heading: "IA de código abierto para Discord",
    developmentStatus: "Actualmente en desarrollo activo",
    readDocs: "Leer la documentación",
    invite: "Invitar a TomoriBot",
    viewGitHub: "Ver en GitHub",
    theme: "Tema",
    language: "Idioma",
    dark: "Oscuro",
    light: "Claro",
    automatic: "Automático",
    home: "Inicio de TomoriBot",
    links: "Enlaces de TomoriBot",
    support: "Apoyar en Ko-fi",
    showcase: "Galería de funciones de TomoriBot",
    chooseFeature: "Elegir una función",
    viewFeature: "Ver",
    galleryInstruction: "Haz clic en la mitad izquierda o derecha para recorrer la galería.",
    guide: "Abre la guía completa de TomoriBot en cualquier idioma publicado.",
    documentationLanguages: "Idiomas de la documentación",
    heroImage: "TomoriBot",
    features: [
      { title: "Múltiples personajes", description: "Usa varios personajes personalizados en un servidor, cada uno con sus propios ajustes, recuerdos y avatares." },
      { title: "Memoria persistente", description: "Conserva contexto útil entre conversaciones, canales y servidores con memorias personales y del servidor." },
      { title: "Generación multimedia", description: "Comprende y genera imágenes, videos cortos y mensajes de voz directamente en Discord." },
      { title: "Herramientas de agente", description: "Busca en la web, programa recordatorios, usa herramientas MCP personalizadas y completa tareas de varios pasos." },
      { title: "Configuración totalmente local", description: "Autoaloja con modelos locales, ComfyUI, SearXNG, servidores de voz e integraciones MCP." },
      { title: "Moderación del servidor", description: "Controla el acceso y los costos con cuotas, permisos, reglas de canal, reglas de rol y herramientas de auditoría." },
      { title: "Más de 200 comandos", description: "Configura personajes, proveedores, prompts, modelos, herramientas, memoria y permisos desde Discord." },
      { title: "Compatibilidad con SillyTavern", description: "Importa preajustes de prompts y tarjetas de personaje de SillyTavern para usarlos directamente en Discord." },
    ],
  },
  "pt-BR": {
    title: "TomoriBot | Agente de IA e bot de roleplay de código aberto para Discord",
    description: "TomoriBot é um bot gratuito e de código aberto para Discord, com memória persistente, múltiplas personas, ferramentas de agente, geração de mídia e suporte a modelos de IA hospedados ou locais.",
    heading: "IA de código aberto para Discord",
    developmentStatus: "Atualmente em desenvolvimento ativo",
    readDocs: "Ler a documentação",
    invite: "Convidar TomoriBot",
    viewGitHub: "Ver no GitHub",
    theme: "Tema",
    language: "Idioma",
    dark: "Escuro",
    light: "Claro",
    automatic: "Automático",
    home: "Página inicial do TomoriBot",
    links: "Links do TomoriBot",
    support: "Apoiar no Ko-fi",
    showcase: "Galeria de recursos do TomoriBot",
    chooseFeature: "Escolher um recurso",
    viewFeature: "Ver",
    galleryInstruction: "Clique na metade esquerda ou direita para percorrer a galeria.",
    guide: "Abra o guia completo do TomoriBot em qualquer idioma publicado.",
    documentationLanguages: "Idiomas da documentação",
    heroImage: "TomoriBot",
    features: [
      { title: "Múltiplas personas", description: "Use vários personagens personalizados em um servidor, cada um com suas próprias configurações, memórias e avatares." },
      { title: "Memória persistente", description: "Mantenha contexto útil entre conversas, canais e servidores com memórias pessoais e do servidor." },
      { title: "Geração de mídia", description: "Entenda e gere imagens, vídeos curtos e mensagens de voz diretamente no Discord." },
      { title: "Ferramentas de agente", description: "Pesquise na web, agende lembretes, use ferramentas MCP personalizadas e conclua tarefas em várias etapas." },
      { title: "Configuração totalmente local", description: "Hospede por conta própria com modelos locais, ComfyUI, SearXNG, servidores de voz e integrações MCP." },
      { title: "Moderação do servidor", description: "Controle acesso e custos com cotas, permissões, regras de canal, regras de cargo e ferramentas de auditoria." },
      { title: "Mais de 200 comandos", description: "Configure personas, provedores, prompts, modelos, ferramentas, memória e permissões pelo Discord." },
      { title: "Suporte ao SillyTavern", description: "Importe predefinições de prompt e cartões de personagem do SillyTavern para uso direto no Discord." },
    ],
  },
  vi: {
    title: "TomoriBot | Tác nhân AI mã nguồn mở và bot nhập vai cho Discord",
    description: "TomoriBot là bot Discord miễn phí, mã nguồn mở với bộ nhớ bền vững, nhiều nhân cách, công cụ tác tử, tạo nội dung đa phương tiện và hỗ trợ mô hình AI lưu trữ hoặc cục bộ.",
    heading: "AI mã nguồn mở cho Discord",
    developmentStatus: "Hiện đang được phát triển tích cực",
    readDocs: "Đọc tài liệu",
    invite: "Mời TomoriBot",
    viewGitHub: "Xem trên GitHub",
    theme: "Giao diện",
    language: "Ngôn ngữ",
    dark: "Tối",
    light: "Sáng",
    automatic: "Tự động",
    home: "Trang chủ TomoriBot",
    links: "Liên kết TomoriBot",
    support: "Ủng hộ trên Ko-fi",
    showcase: "Thư viện tính năng TomoriBot",
    chooseFeature: "Chọn tính năng",
    viewFeature: "Xem",
    galleryInstruction: "Nhấp vào nửa bên trái hoặc phải để di chuyển trong thư viện.",
    guide: "Mở hướng dẫn TomoriBot đầy đủ bằng bất kỳ ngôn ngữ đã xuất bản nào.",
    documentationLanguages: "Ngôn ngữ tài liệu",
    heroImage: "TomoriBot",
    features: [
      { title: "Nhiều nhân cách", description: "Dùng nhiều nhân vật tùy chỉnh trong một máy chủ, mỗi nhân vật có thiết lập, ký ức và ảnh đại diện riêng." },
      { title: "Bộ nhớ bền vững", description: "Giữ ngữ cảnh hữu ích qua các cuộc trò chuyện, kênh và máy chủ bằng bộ nhớ máy chủ và cá nhân." },
      { title: "Tạo nội dung đa phương tiện", description: "Hiểu và tạo hình ảnh, video ngắn và tin nhắn thoại trực tiếp trong Discord." },
      { title: "Công cụ tác tử", description: "Tìm kiếm web, lên lịch nhắc nhở, dùng công cụ MCP tùy chỉnh và hoàn thành tác vụ nhiều bước." },
      { title: "Thiết lập hoàn toàn cục bộ", description: "Tự lưu trữ với mô hình cục bộ, ComfyUI, SearXNG, máy chủ giọng nói và tích hợp MCP." },
      { title: "Kiểm duyệt máy chủ", description: "Kiểm soát quyền truy cập và chi phí bằng hạn ngạch, quyền hạn, quy tắc kênh, quy tắc vai trò và công cụ kiểm toán." },
      { title: "Hơn 200 lệnh", description: "Cấu hình nhân cách, nhà cung cấp, lời nhắc, mô hình, công cụ, bộ nhớ và quyền hạn từ Discord." },
      { title: "Hỗ trợ SillyTavern", description: "Nhập cấu hình lời nhắc và thẻ nhân vật SillyTavern để dùng trực tiếp trong Discord." },
    ],
  },
};
